/**
 * Style-prop shorthands used across the design system. Inlined (rather than
 * importing `@tamagui/shorthands`) so the dependency surface matches the spec's
 * library list exactly.
 */
export const shorthands = {
  f: 'flex',
  ai: 'alignItems',
  jc: 'justifyContent',
  fd: 'flexDirection',
  fw: 'flexWrap',
  gap: 'gap',
  pos: 'position',
  bg: 'backgroundColor',
  br: 'borderRadius',
  bw: 'borderWidth',
  bc: 'borderColor',
  p: 'padding',
  px: 'paddingHorizontal',
  py: 'paddingVertical',
  pt: 'paddingTop',
  pb: 'paddingBottom',
  pl: 'paddingLeft',
  pr: 'paddingRight',
  m: 'margin',
  mx: 'marginHorizontal',
  my: 'marginVertical',
  mt: 'marginTop',
  mb: 'marginBottom',
  ml: 'marginLeft',
  mr: 'marginRight',
  w: 'width',
  h: 'height',
  maw: 'maxWidth',
  mah: 'maxHeight',
  miw: 'minWidth',
  mih: 'minHeight',
  ov: 'overflow',
  zi: 'zIndex',
  als: 'alignSelf',
  fs: 'fontSize',
  fow: 'fontWeight',
  ff: 'fontFamily',
  lh: 'lineHeight',
  ls: 'letterSpacing',
  ta: 'textAlign',
  col: 'color',
  o: 'opacity',
} as const;
